import assert from 'node:assert/strict';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { execFile } from 'node:child_process';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const execute = promisify(execFile);
const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const cli = path.join(root, 'bin', 'readme-port.mjs');

async function run(args, cwd) {
  return execute(process.execPath, [cli, ...args], { cwd, encoding: 'utf8' });
}

test('CLI initializes, builds, preserves manual content, checks, doctors, and ejects', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'readme-port-'));
  await run(['init', '--kind', 'project'], directory);
  const configPath = path.join(directory, 'readme-port.config.json');
  assert.match(await readFile(configPath, 'utf8'), /project\/flagship/);

  await run(['build', '--force'], directory);
  const readmePath = path.join(directory, 'README.md');
  const first = await readFile(readmePath, 'utf8');
  assert.match(first, /Generated by ReadmePort/);

  await writeFile(readmePath, first.replace(
    '[readme-port-manual-end-project-notes]: # (/readme-port:manual)',
    'Keep this manual value.\n[readme-port-manual-end-project-notes]: # (/readme-port:manual)',
  ));
  await run(['build'], directory);
  assert.match(await readFile(readmePath, 'utf8'), /Keep this manual value\./);

  await run(['check'], directory);
  await run(['doctor'], directory);
  await run(['eject'], directory);
  const updatedConfig = JSON.parse(await readFile(configPath, 'utf8'));
  assert.match(updatedConfig.customTemplate, /^\.readme-port/);
});

test('CLI refuses to replace an unrecognized README without force', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'readme-port-safe-'));
  await run(['init'], directory);
  await writeFile(path.join(directory, 'README.md'), '# Hand-written\n');
  await assert.rejects(() => run(['build'], directory), /Refusing to overwrite/);
});

test('CLI refuses malformed manual regions before content can be lost', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'readme-port-markers-'));
  await run(['init'], directory);
  await run(['build', '--force'], directory);
  const readmePath = path.join(directory, 'README.md');
  const content = await readFile(readmePath, 'utf8');
  await writeFile(readmePath, content.replace('[readme-port-manual-end-project-notes]: # (/readme-port:manual)', ''));
  await assert.rejects(() => run(['build'], directory), /manual regions are invalid/);
  await assert.rejects(() => run(['doctor'], directory), /manual regions are invalid/);
});

test('CLI rejects unknown options and invalid kinds without writing defaults', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'readme-port-options-'));
  await assert.rejects(() => run(['init', '--kind', 'nonsense'], directory), /--kind must be/);
  await run(['init'], directory);
  await assert.rejects(() => run(['build', '--ouput', 'intended.md', '--force'], directory), /Unknown option/);
  await assert.rejects(() => readFile(path.join(directory, 'README.md'), 'utf8'));
});

test('multi-provider builds honor template and mode overrides', async () => {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'readme-port-all-'));
  await run(['init'], directory);
  await run([
    'build', '--provider', 'all', '--template', 'project/minimal',
    '--mode', 'portable', '--output', 'dist', '--force',
  ], directory);
  const github = await readFile(path.join(directory, 'dist', 'github', 'README.md'), 'utf8');
  assert.doesNotMatch(github, /<div align=/);
  assert.doesNotMatch(github, /At a glance/);
  assert.match(github, /## Features/);
  await assert.rejects(
    () => run(['build', '--provider', 'all', '--stdout'], directory),
    /--stdout cannot be combined/,
  );
});
