name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: node:24-bookworm
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - run: npm run ci
