export const GENERATED_MARKER = '[readme-port-generated]: # (Generated by ReadmePort; edit the configuration and regenerate.)';

const REGION_PATTERN = /^\[readme-port-manual-start-([a-zA-Z0-9._-]+)\]: # \(readme-port:manual\)\r?\n([\s\S]*?)^\[readme-port-manual-end-\1\]: # \(\/readme-port:manual\)$/gm;
const OPENING_PATTERN = /^\[readme-port-manual-start-([a-zA-Z0-9._-]+)\]: # \(readme-port:manual\)$/gm;
const CLOSING_PATTERN = /^\[readme-port-manual-end-([a-zA-Z0-9._-]+)\]: # \(\/readme-port:manual\)$/gm;
const MARKER_PATTERN = /^\[readme-port-manual-(start|end)-([^\]\r\n]*)\]: # \((\/?readme-port:manual)\)$/gm;
const VALID_REGION_ID = /^[a-zA-Z0-9._-]+$/;

export function isGeneratedReadme(content) {
  return typeof content === 'string' && content.includes(GENERATED_MARKER);
}

export function extractManualRegions(content = '') {
  const problems = inspectManualRegions(content);
  if (problems.length > 0) {
    throw new Error(`Cannot extract manual content:\n- ${problems.join('\n- ')}`);
  }
  const regions = new Map();
  let match;
  REGION_PATTERN.lastIndex = 0;
  while ((match = REGION_PATTERN.exec(content)) !== null) {
    const [, id, body] = match;
    if (regions.has(id)) {
      throw new Error(`Duplicate manual region: ${id}`);
    }
    regions.set(id, body);
  }
  return regions;
}

export function restoreManualRegions(generated, previous = '') {
  const problems = inspectManualRegions(previous);
  if (problems.length > 0) {
    throw new Error(`Cannot preserve manual content:\n- ${problems.join('\n- ')}`);
  }
  const previousRegions = extractManualRegions(previous);
  if (previousRegions.size === 0) return generated;

  REGION_PATTERN.lastIndex = 0;
  return generated.replace(REGION_PATTERN, (whole, id) => {
    if (!previousRegions.has(id)) return whole;
    return `[readme-port-manual-start-${id}]: # (readme-port:manual)\n${previousRegions.get(id)}[readme-port-manual-end-${id}]: # (/readme-port:manual)`;
  });
}

export function inspectManualRegions(content = '') {
  const openings = [...content.matchAll(OPENING_PATTERN)].map((match) => match[1]);
  const closings = [...content.matchAll(CLOSING_PATTERN)].map((match) => match[1]);
  const problems = [];
  if (openings.length !== closings.length) {
    problems.push(`Manual region markers are unbalanced (${openings.length} open, ${closings.length} close)`);
  }
  const duplicates = openings.filter((id, index) => openings.indexOf(id) !== index);
  if (duplicates.length > 0) {
    problems.push(`Duplicate manual region IDs: ${[...new Set(duplicates)].join(', ')}`);
  }
  const mismatched = [...new Set([...openings, ...closings])]
    .filter((id) => openings.filter((value) => value === id).length !== closings.filter((value) => value === id).length);
  if (mismatched.length > 0 && openings.length === closings.length) {
    problems.push(`Manual region IDs do not match: ${mismatched.join(', ')}`);
  }

  const stack = [];
  for (const match of content.matchAll(MARKER_PATTERN)) {
    const [, type, id, markerValue] = match;
    const validValue = type === 'start' ? 'readme-port:manual' : '/readme-port:manual';
    if (!VALID_REGION_ID.test(id)) {
      problems.push(`Invalid manual region ID: ${id || '(empty)'}`);
      continue;
    }
    if (markerValue !== validValue) {
      problems.push(`Invalid ${type} marker for manual region: ${id}`);
      continue;
    }
    if (type === 'start') {
      if (stack.length > 0) {
        problems.push(`Manual regions cannot be nested: ${id} opens before ${stack.at(-1)} closes`);
      }
      stack.push(id);
      continue;
    }
    const expected = stack.at(-1);
    if (!expected) {
      problems.push(`Manual region closes before it opens: ${id}`);
      continue;
    }
    if (expected && expected !== id) {
      problems.push(`Manual regions close out of order: expected ${expected}, found ${id}`);
      const matchingIndex = stack.lastIndexOf(id);
      if (matchingIndex >= 0) stack.splice(matchingIndex, 1);
      continue;
    }
    if (expected === id) stack.pop();
  }
  if (stack.length > 0 && openings.length === closings.length) {
    problems.push(`Manual regions remain open after marker ordering: ${[...new Set(stack)].join(', ')}`);
  }
  return problems;
}
